name: Onboarding to Open Austin
description: Use this checklist to onboard yourself to Open Austin.
title: "{Name}: Onboarding"
labels: ["onboarding"]
assignees:
  - octocat

sections:
  - heading: Welcome to Open Austin onboarding
    content: >
      Welcome to Open Austin's onboarding checklist. Submit this ticket as-is to get started on onboarding tasks.

  - heading: Join our tools
    tasks:
      - text: "Join the Open Austin Slack"
        link: "https://join.slack.com/t/open-austin/shared_invite/zt-1xrl6n1fo-5E7~JqTv1bdq5liqLuEXnQ"
      - text: "Turn on notifications for channel of the Community of Practice you align with"
        link: "https://slack.com/help/articles/360056534254-Manage-notifications-for-specific-channels-and-direct-messages"
      - text: "Optional: Follow Open Austin on LinkedIn and/or Instagram"
        links:
          - "https://www.linkedin.com/company/open-austin/"
          - "https://www.instagram.com/open_austin"

  - heading: Tell us about yourself
    tasks:
      - text: "Choose and create your contributor profile. You're responsible for updating it throughout your time at Open Austin."
        options:
          - role: "Designer"
            link: "https://github.com/open-austin/practice-designers/issues/new?assignees=jcklpe&labels=design%2Ccontributor+profile&projects=&template=design-contributor-profile.yaml&title=%7BYour+Name%7D%3A+Design+Contributor+Profile"
          - role: "Developer"
            link: "https://github.com/open-austin/practice-devs/issues/new?template=contributor-profile.yaml"
          - role: "Data scientist"
            link: "https://github.com/open-austin/practice-data-nerds/issues/new?template=contributor-profile.yaml"
          - role: "Product/project manager"
            link: "https://github.com/open-austin/practice-product/issues/new?template=contributor-profile.yaml"
      - text: "Introduce yourself in #general on Slack (you can include your contributor profile)."
      - text: "Join the volunteer roster by sending a message to #oa-admin"
        example: "I’m a new YOUR ROLE and I attended DATE org intro. My email address is EMAIL ADDRESS."

  - heading: Get started building tech for good
    tasks:
      - text: "Join your Community of Practice channel and turn on notifications"
        link: "https://slack.com/help/articles/360056534254-Manage-notifications-for-specific-channels-and-direct-messages"
      - text: "Explore open roles"
        link: "https://github.com/orgs/open-austin/projects/6"